name = "metal-pathfinder"
compatibility_date = "2024-12-20"

[env.production]
kv_namespaces = [
  { binding = "SESSION", id = "YOUR_KV_NAMESPACE_ID", preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" }
]

# Environment variables (these will be set in Cloudflare dashboard)
[env.production.vars]
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_KEY = "your-supabase-key"  
# SPOTIFY_CLIENT_ID = "your-spotify-client-id"
# SPOTIFY_CLIENT_SECRET = "your-spotify-client-secret"
# OPENAI_API_KEY = "your-openai-api-key" 